version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27018:27017
    restart: always
    networks:
      - web
volumes:
  mongodb_data_container:

networks:
  web:
    driver: bridge