version: '3'

services:
  competitions:
    build: ./competitions
    depends_on:
      - mongodb
    links: [ 'mongodb' ]
    restart: always
    environment:
      MONGODB_URI: mongodb://mongodb:27017
    ports:
      - "8080:8080"
    networks:
      - web

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27018:27017
    restart: always
    networks:
      - web
volumes:
  mongodb_data_container:


networks:
  web:
    driver: bridge
